version: '3'

services:
  server:
    build: './server'
    volumes:
      - ./product:/user/src/app
    ports:
      - 5000:5000
  client:
    build: './client'
    volumes:
    ports:
      - 3000:3000
    depends_on:
      - server
